<?php

declare(strict_types=1);

return [
    'title' => 'Invoice :number',

    'label' => [
        'seller' => 'Seller',
        'buyer' => 'Buyer',
        'issued_at' => 'Issue date',
        'sale_date' => 'Sale date',
        'due_at' => 'Due date',
        'item_name' => 'Item',
        'qty' => 'Qty',
        'unit' => 'Unit',
        'unit_price' => 'Unit price',
        'net' => 'Net',
        'vat_rate' => 'VAT',
        'vat' => 'VAT amt',
        'gross' => 'Gross',
        'net_total' => 'Net total',
        'vat_total' => 'VAT total',
        'gross_total' => 'Amount due',
        'payment_to' => 'Pay to account',
        'payment_title' => 'Use as title: :number',
        'transport_details' => 'Service details',
    ],

    'footer' => 'Document generated by :app',
];
