<?php

declare(strict_types=1);

return [
    'title' => 'Transport quote :number',
    'number_label' => 'QUOTE NO.',
    'issued' => 'Issued',
    'valid_until' => 'Valid until',

    'heading' => 'Horse transport quote',
    'subtitle' => 'Pricing valid for the given date and within the validity period.',

    'section' => [
        'customer' => 'Customer',
        'route' => 'Route',
        'pricing' => 'Pricing',
        'terms' => 'Terms',
    ],

    'label' => [
        'name' => 'Full name',
        'company' => 'Company',
        'tax_id' => 'Tax ID',
        'email' => 'Email',
        'phone' => 'Phone',
        'address' => 'Address',
        'from' => 'From',
        'to' => 'To',
        'date' => 'Date',
        'distance' => 'Distance',
        'duration' => 'Travel time',
        'round_trip' => 'Round trip',
        'component' => 'Item',
        'amount' => 'Amount',
        'base_cost' => 'Base cost',
        'fuel_surcharge' => 'Fuel surcharge',
        'minimum_adjustment' => 'Minimum-charge adjustment',
        'net_total' => 'Net total',
        'vat' => 'VAT (:rate%)',
        'gross_total' => 'Gross total',
    ],

    'value' => [
        'yes' => 'Yes',
        'no' => 'No',
    ],

    'footer' => [
        'generated' => 'Document generated by :app',
    ],
];
